
from obter_dados_gam_eva import obter_evadidos_iniciacao_presencial_gam
mat =  obter_evadidos_iniciacao_presencial_gam()


#Matricula 
print(mat)

{'fev_tecni_iti_presen_mat_1 Gratuidade Regimental': 58, 'fev_tecni_iti_presen_mat_2 Gratuidade Não Regimental': 0, 'fev_tecni_iti_presen_mat_3 Convênio': 0, 'fev_tecni_iti_presen_mat_9 Pago por Pessoa Fisica ou Empresa': 1}
 
 
{'jan_inicia_presen_ha_1 Gratuidade Regimental': 0, 'jan_inicia_presen_ha_2 Gratuidade Não Regimental': 0, 'jan_inicia_presen_ha_3 Convênio': 0, 'jan_inicia_presen_ha_9 Pago por Pessoa Fisica ou Empresa': 0, 'fev_inicia_presen_ha_1 Gratuidade Regimental': 0, 'fev_inicia_presen_ha_2 Gratuidade Não Regimental': 1080, 'fev_inicia_presen_ha_3 Convênio': 0, 'fev_inicia_presen_ha_9 Pago por Pessoa Fisica ou Empresa': 0, 'mar_inicia_presen_ha_1 Gratuidade Regimental': 0, 'mar_inicia_presen_ha_2 Gratuidade Não Regimental': 2230, 'mar_inicia_presen_ha_3 Convênio': 0, 'mar_inicia_presen_ha_9 Pago por Pessoa Fisica ou Empresa': 0, 'abr_inicia_presen_ha_1 Gratuidade Regimental': 0, 'abr_inicia_presen_ha_2 Gratuidade Não Regimental': 1630, 'abr_inicia_presen_ha_3 Convênio': 0, 'abr_inicia_presen_ha_9 Pago por Pessoa Fisica ou Empresa': 0, 'mai_inicia_presen_ha_1 Gratuidade Regimental': 0, 'mai_inicia_presen_ha_2 Gratuidade Não Regimental': 1395, 'mai_inicia_presen_ha_3 Convênio': 0, 'mai_inicia_presen_ha_9 Pago por Pessoa Fisica ou Empresa': 0, 'jun_inicia_presen_ha_1 Gratuidade Regimental': 0, 'jun_inicia_presen_ha_2 Gratuidade Não Regimental': 1400, 'jun_inicia_presen_ha_3 Convênio': 0, 'jun_inicia_presen_ha_9 Pago por Pessoa Fisica ou Empresa': 0, 'jul_inicia_presen_ha_1 Gratuidade Regimental': 0, 'jul_inicia_presen_ha_2 Gratuidade Não Regimental': 700, 'jul_inicia_presen_ha_3 Convênio': 0, 'jul_inicia_presen_ha_9 Pago por Pessoa Fisica ou Empresa': 0, 'ago_inicia_presen_ha_1 Gratuidade Regimental': 0, 'ago_inicia_presen_ha_2 Gratuidade Não Regimental': 0, 'ago_inicia_presen_ha_3 Convênio': 0, 'ago_inicia_presen_ha_9 Pago por Pessoa Fisica ou Empresa': 0, 'set_inicia_presen_ha_1 Gratuidade Regimental': 0, 'set_inicia_presen_ha_2 Gratuidade Não Regimental': 0, 'set_inicia_presen_ha_3 Convênio': 0, 'set_inicia_presen_ha_9 Pago por Pessoa Fisica ou Empresa': 0, 'out_inicia_presen_ha_1 Gratuidade Regimental': 0, 'out_inicia_presen_ha_2 Gratuidade Não Regimental': 0, 'out_inicia_presen_ha_3 Convênio': 0, 'out_inicia_presen_ha_9 Pago por Pessoa Fisica ou Empresa': 0, 'nov_inicia_presen_ha_1 Gratuidade Regimental': 0, 'nov_inicia_presen_ha_2 Gratuidade Não Regimental': 0, 'nov_inicia_presen_ha_3 Convênio': 0, 'nov_inicia_presen_ha_9 Pago por Pessoa Fisica ou Empresa': 0, 'dez_inicia_presen_ha_1 Gratuidade Regimental': 0, 'dez_inicia_presen_ha_2 Gratuidade Não Regimental': 0, 'dez_inicia_presen_ha_3 Convênio': 0, 'dez_inicia_presen_ha_9 Pago por Pessoa Fisica ou Empresa': 0}